### ISSUE TITLE
fontlarni qollashdagi hatolar

### ISSUE THREAD

**Issue by otabek-oktamov** [Doniyorbek-Coder/money-transfers-page#1]
fontlarni internet orqali ulaganingiz uchun internet sekin bolgan qurilmalarda fontlar 2 hil
boshida oz holatida keyin siz bergan font da ko'rinadi buni oldini olish uchun stylelarga  font-display:swap; berish kerak

**Comment by Doniyorbek-Coder** [comment]
Rahmat !!!

вт, 9 мар. 2021 г. в 11:03, Otabek <notifications@github.com>:
